name: CI

on: [push, pull_request]

jobs:
  job_build:
    name: Compilation
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make COIN=zcash && mv bin/ zcash-bin/

      - name: Upload Zcash app binary
        uses: actions/upload-artifact@v2
        with:
          name: zcash-app
          path: zcash-bin

  job_test:
    name: Tests
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download ZCash app binary
        uses: actions/download-artifact@v2
        with:
          name: zcash-app
          path: tests/zcash-bin

      - name: Download Zcash app binary
        uses: actions/download-artifact@v2
        with:
          name: zcash-app
          path: tests/zcash-bin

      - name: Run tests
        run: |
          cd tests && pip install -r requirements.txt && SPECULOS=/speculos/speculos.py pytest
