name: CI

on: [push, pull_request]

jobs:
  job_build:
    name: Compilation
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make COIN=zcash&& mv bin/ zcash-bin/

      - name: Upload Zcash app binary
        uses: actions/upload-artifact@v2
        with:
          name: zcash-app
          path: zcash-bin
